Connected to psychopy_enV (Python 3.8.20)

In [ ]:
import explorepy
import time
from explorepy.stream_processor import TOPICS
import numpy as np
def main():
    #Headset Setup
    
    headset_name = 'Explore_849D' 
    sample_rate = 250
    channel_dict = {
            0: 'TP9',
            1: 'Fz', 2: 'C3', 3: 'Cz', 4: 'C4', 5: 'P3', 6: 'P4', 7: 'Fz', 8: 'TP10'
        }
    explorer = explorepy.Explore()
    explorer.connect(device_name=headset_name)
    explorer.set_sampling_rate(sample_rate)

    global eeg_list
    eeg_list = []

    def eeg_callback(packet):
        global time_data
        t_vector , exg_data = packet.get_data()
        eeg_list.append(exg_data)
    
    explorer.stream_processor.subscribe(callback=eeg_callback, topic=TOPICS.raw_ExG)

    print('30 sec')
    time.sleep(5)

    global eeg_raw
    eeg_raw = np.concatenate(eeg_list, axis= -1)
    print(eeg_raw)
    




    
main()

2025-04-11 13:30:39,013 - [INFO] - Connecting to Explore_849D ...
2025-04-11 13:30:43,239 - [INFO] - Waiting for device info packet...
2025-04-11 13:30:44,243 - [INFO] - Device info packet has been received. Connection has been established. Streaming...
2025-04-11 13:30:44,245 - [INFO] - Device info: {'device_name': 'Explore_849D', 'firmware_version': '2.1.5', 'adc_mask': [1, 1, 1, 1, 1, 1, 1, 1], 'sampling_rate': 250.0}
2025-04-11 13:30:44,248 - [INFO] - Sending the command: Host timestamp
2025-04-11 13:30:44,250 - [INFO] - Command has been sent successfully.
2025-04-11 13:30:44,251 - [INFO] - Sending the command: Set sampling rate command
2025-04-11 13:30:44,252 - [INFO] - Command has been sent successfully.
2025-04-11 13:30:44,253 - [INFO] - waiting for ack and status messages...
2025-04-11 13:30:45,263 - [INFO] - Command has been received by Explore.
2025-04-11 13:30:45,266 - [INFO] - Command has been successfully executed by the device.


30 sec
[[-373711.68 -378316.02 -371440.26 ... -362382.41 -371590.32 -378278.83]
 [-372922.32 -374081.85 -372471.   ... -369779.11 -372013.57 -373906.94]
 [-372984.17 -374152.09 -372952.84 ... -370536.71 -372371.34 -373924.01]
 ...
 [-371942.52 -373857.02 -371357.49 ... -367413.04 -370931.72 -373632.24]
 [-366201.44 -374225.66 -362935.63 ... -347925.18 -363571.02 -375130.17]
 [-372182.46 -374865.2  -373577.45 ... -368211.69 -370700.02 -373956.06]]


In [ ]:
print(eeg_raw)

[[-373711.68 -378316.02 -371440.26 ... -362382.41 -371590.32 -378278.83]
 [-372922.32 -374081.85 -372471.   ... -369779.11 -372013.57 -373906.94]
 [-372984.17 -374152.09 -372952.84 ... -370536.71 -372371.34 -373924.01]
 ...
 [-371942.52 -373857.02 -371357.49 ... -367413.04 -370931.72 -373632.24]
 [-366201.44 -374225.66 -362935.63 ... -347925.18 -363571.02 -375130.17]
 [-372182.46 -374865.2  -373577.45 ... -368211.69 -370700.02 -373956.06]]


In [ ]:
eeg_raw.shape

(8, 1248)

In [ ]:
import mne

In [ ]:
info = mne.create_info(ch_names=['ch1', 'ch2', 'ch3', 'ch4', 'ch5', 'ch6', 'ch7', 'ch8'], sfreq=250, ch_types='eeg')
mne_data = mne.io.RawArray(eeg_raw, info)

Creating RawArray with float64 data, n_channels=8, n_times=1248
    Range : 0 ... 1247 =      0.000 ...     4.988 secs
Ready.
