Connected to psychopy_enV (Python 3.8.20)

In [ ]:
import explorepy
import time
from explorepy.stream_processor import TOPICS
import numpy as np
def main():
    #Headset Setup
    
    headset_name = 'Explore_849D' 
    sample_rate = 250
    channel_dict = {
            0: 'TP9',
            1: 'Fz', 2: 'C3', 3: 'Cz', 4: 'C4', 5: 'P3', 6: 'P4', 7: 'Fz', 8: 'TP10'
        }
    explorer = explorepy.Explore()
    explorer.connect(device_name=headset_name)
    explorer.set_sampling_rate(sample_rate)

    global eeg_list
    eeg_list = []

    def eeg_callback(packet):
        global time_data
        t_vector , exg_data = packet.get_data()
        eeg_list.append(exg_data)
    
    explorer.stream_processor.subscribe(callback=eeg_callback, topic=TOPICS.raw_ExG)

    print('30 sec')
    time.sleep(20)

    global eeg_raw
    eeg_raw = np.concatenate(eeg_list, axis= -1)
    print(eeg_raw)
    explorer.stop_recording()
    explorer.disconnect()
    




    
main()

2025-04-21 17:34:05,144 - [INFO] - Connecting to Explore_849D ...
2025-04-21 17:34:11,006 - [INFO] - Waiting for device info packet...
2025-04-21 17:34:12,008 - [INFO] - Device info packet has been received. Connection has been established. Streaming...
2025-04-21 17:34:12,011 - [INFO] - Device info: {'device_name': 'Explore_849D', 'firmware_version': '2.1.5', 'adc_mask': [1, 1, 1, 1, 1, 1, 1, 1], 'sampling_rate': 250.0}
2025-04-21 17:34:12,012 - [INFO] - Sending the command: Host timestamp
2025-04-21 17:34:12,014 - [INFO] - Command has been sent successfully.
2025-04-21 17:34:12,015 - [INFO] - Sending the command: Set sampling rate command
2025-04-21 17:34:12,016 - [INFO] - Command has been sent successfully.
2025-04-21 17:34:12,017 - [INFO] - waiting for ack and status messages...
2025-04-21 17:34:13,025 - [INFO] - Command has been received by Explore.
2025-04-21 17:34:13,026 - [INFO] - Command has been successfully executed by the device.


30 sec
[[-372285.08 -365561.29 -367845.29 ... -371151.3  -366147.04 -370439.14]
 [-370926.42 -355701.73 -360438.01 ... -368638.75 -357162.8  -366582.2 ]
 [-373879.76 -367170.71 -369114.16 ... -372892.85 -367808.72 -371765.85]
 ...
 [-372776.27 -368584.25 -370208.12 ... -371847.24 -368810.32 -371722.46]
 [-364941.5  -360078.   -361701.01 ... -364242.45 -360674.09 -363772.77]
 [-372780.42 -368146.51 -370336.34 ... -371823.4  -368595.17 -372250.46]]


2025-04-21 17:46:50,312 - [WARNING] - Device has been disconnected! Scanning for the last connected device...
2025-04-21 17:46:50,321 - [WARNING] - Couldn't connect to the device. Trying to reconnect...


In [10]:
print(eeg_raw)

[[-382536.12 -390156.27 -377562.9  ... -360598.27 -374593.73 -384394.6 ]
 [-383876.32 -398967.5  -375397.92 ... -348170.04 -371766.8  -388881.21]
 [-383508.78 -391634.08 -379987.71 ... -367824.41 -374928.61 -380919.07]
 ...
 [-381727.93 -386018.04 -378099.77 ... -369861.69 -376575.28 -381098.84]
 [-373776.39 -379179.95 -370751.52 ... -358807.32 -367949.53 -374098.3 ]
 [-382968.28 -387367.82 -378158.9  ... -368344.3  -377502.68 -383068.89]]


In [18]:
eeg_raw.shape

(8, 5008)

In [12]:
import mne

In [19]:
info = mne.create_info(ch_names=['ch1', 'ch2', 'ch3', 'ch4', 'ch5', 'ch6', 'ch7', 'ch8'], sfreq=250, ch_types='eeg')
mne_data = mne.io.RawArray(eeg_raw, info)

Creating RawArray with float64 data, n_channels=8, n_times=5008
    Range : 0 ... 5007 =      0.000 ...    20.028 secs
Ready.
